# yaml-language-server: $schema=./config.schema.json

##
# NOTE: Possible provider values: "highlight-js", "prism-js".
# - https://highlightjs.org
# - https://prismjs.com
#
syntax_highlighting:
  # provider: highlight-js
  provider: prism-js
