version: "3"

tasks:
  build:
    cmds:
      - bundle exec ruby scripts/build.rb

  install:
    cmds:
      - bundle install

  start:
    cmds:
      - task: start:dev

  start:dev:
    cmds:
      - PORT=8100 bundle exec ruby scripts/server.rb

  start:build:
    cmds:
      - task: build
      - ruby -run -e httpd dist -p 8101
