# frozen_string_literal: true

require_relative "services/build_page"
require_relative "services/build_pages"
require_relative "services/build_pages_concurrently"
require_relative "services/build_pages_sequentially"
require_relative "services/check_network"
require_relative "services/collect_asset"
require_relative "services/convert_locs_to_uris"
require_relative "services/convert_uri_to_dist_parent_path"
require_relative "services/convert_uri_to_dist_path"
require_relative "services/fetch_http_response"
require_relative "services/find_free_port"
require_relative "services/kill_process"
require_relative "services/parse_sitemap_xml"
require_relative "services/post_process_page"
require_relative "services/quit_browser"
require_relative "services/read_file_content"
require_relative "services/remove_folder"
require_relative "services/resolve_locs"
require_relative "services/resolve_locs_from_argv"
require_relative "services/resolve_locs_from_sitemap"
require_relative "services/save_asset"
require_relative "services/save_assets"
require_relative "services/save_llms_txt"
require_relative "services/save_page"
require_relative "services/save_sitemap"
require_relative "services/spawn_dev_server"
require_relative "services/touch_folder"
require_relative "services/wait_server_healthcheck"
require_relative "services/write_binary_file"
require_relative "services/write_file"

require_relative "services/build"
