# yaml-language-server: $schema=./config.schema.json

base_url: "https://userdocs.convenientservice.org"
base_path: "/comprehensive_docs"

syntax_highlighting:
  # NOTE: Possible provider values: "highlight-js", "prism-js".
  # - https://highlightjs.org
  # - https://prismjs.com
  # provider: highlight-js
  provider: prism-js

code_links:
  AssertFileExists: /docs/examples/services.html#assert-file-exists
  AssertFileNotEmpty: /docs/examples/services.html#assert-file-not-empty
  ReadFileContent: /docs/examples/services.html#read-file-content
  FindUser: /docs/examples/services.html#find-user
