# yaml-language-server: $schema=./config.schema.json

##
# NOTE: Possible provider values: "highlight-js", "prism-js".
# - https://highlightjs.org
# - https://prismjs.com
#
code_links:
  AssertFileExists: /docs/examples/services.html#assert-file-exists
  AssertFileNotEmpty: /docs/examples/services.html#assert-file-not-empty
  ReadFileContent: /docs/examples/services.html#read-file-content
  FindUser: /docs/examples/services.html#find-user

syntax_highlighting:
  # provider: highlight-js
  provider: prism-js
