source 'https://rubygems.org'

gem 'sinatra', '4.2.1'
gem 'sinatra-contrib', '4.2.1'
gem 'puma', '8.0.0'
gem 'rackup', '2.3.1'
gem 'ferrum', '0.17.2'
gem 'rexml', '3.4.4'
gem 'retriable', '3.1.2'
gem 'concurrent-ruby', '1.3.5'

gem 'convenient_service', '0.24.0'
gem 'dry-initializer', '3.2.0'
gem 'memo_wise', '1.13.0'
gem 'awesome_print', '1.9.2'
gem 'activemodel', '8.1.3'

gem 'nokogiri'

gem 'debug'
