version: "3"

tasks:
  build:
    cmds:
      - bundle exec ruby lib/cs_docs/builder.rb {{.CLI_ARGS}}

  install:
    cmds:
      - bundle install

  start:
    cmds:
      - task start:dev

  start:dev:
    cmds:
      - PORT=8100 bundle exec ruby lib/cs_docs/dev_server.rb

  start:build:
    cmds:
      - task build -- {{.CLI_ARGS}} && ruby -run -e httpd dist -p 8101
